### ISSUE TITLE
Default arguments to minimizer standard

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#102]
Any `*args, **kwargs` passed to a `.execute` method are passed to the minimizer wrapped. But some of these might be given default values by `symfit`, and some might even be of limit to the user.

As a standard for developers I therefore propose using the `symfit.core.support.keywordonly` decorator, which I used as follows in `ConstrainedNumericalLeastSquares`:
```python
class ConstrainedNumericalLeastSquares(Minimize, HasCovarianceMatrix):
    @keywordonly(tol=1e-9)
    def execute(self, *args, **kwargs):
        # do preperations
        ans = minimize(
            self.error_func,
            self.initial_guesses,
            method=method,
            args=(self.independent_data, self.dependent_data, self.sigma_data,),
            bounds=self.model.bounds,
            constraints=self.scipy_constraints,
            jac=self.eval_jacobian if hasattr(self.model, 'numerical_jacobian') else None,
            # jac=self.eval_jacobian,
            *args,
            **kwargs
        )
```

This way, all sanity checking on this is handled by the decorator, and if nothing is provided by the user it takes the default value.

I think this is the way to go because it:
- provides an elegant and readable way to set default values.
- guarantees that the given keywords are present in **kwargs
- forces users to call with keyword arguments rather than ordered arguments, which is the only sensible way to do this. I would therefore add that `*args` should no longer be supported here.
- it protects the arguments specified by `symfit` itself.

@Pitje06, do you see any issues with this? (http://symfit.readthedocs.io/en/latest/module_docs.html#symfit.core.support.keywordonly)

**Comment by Pitje06** [comment]
Agreed.
