### ISSUE TITLE
Implementation With Some Models

### ISSUE THREAD

**Issue by endytc** [tBuLi/symfit#113]
Sorry, I do not have sufficient in statistical science.
I am confused when I will implementation this model, how do I get the value of the loading factor (L) and error value (Ψ/Psi)?
I'm capturing this image from APPLIED MULTIVARIATE
STATSTICALANALYS (RICHARD A. JOHNSON) on page 529
thank you for your attention. :smile: 
![image](https://cloud.githubusercontent.com/assets/1209684/24028674/7acdb31c-0b03-11e7-8745-559ee5102284.png)
![image](https://cloud.githubusercontent.com/assets/1209684/24028743/006cae88-0b04-11e7-924d-19a68a4e72f9.png)

**Comment by tBuLi** [comment]
This is not a Q&A forum, the issue tracker is only for issues with the software. Please use another website for questions such as this, like for example [http://stackoverflow.com](http://stackoverflow.com) (or in this case probably on one of it's physics subsites, because your question is more about physics than programming). I am also active there, so perhaps I could answer it there.

**Comment by endytc** [comment]
Ok, thank's @tBuLi.
this is not about physics, but statistic, Multivariate Analysis.

**Comment by pckroon** [comment]
Still not about symfit. There's a mathematics stacoverflow and a statistics stackoverflow page, both of which would be infinitely more suitable for this question than here.

**Comment by endytc** [comment]
@pckroon Yes, I see. I asked here hope to get answers how can symfit to implementation my model.

**Comment by pckroon** [comment]
Then you should ask a more precise question, like this:
I have a model described by this (python) function. I want to fit this model to this data. How do I do that using Symfit? Will this give me the correct errors and covariances for my parameters?
Or:
I have a model described by this (python) function. How can I minimize this function with respect to these parameters using Symfit? 
Etc.

**Comment by endytc** [comment]
hehe,, sorry and thank's for your correction @pckroon :smile: 
so, can you give me the solution @pckroon @tBuLi ? symfit can resolve it or no?

**Comment by pckroon** [comment]
Please read my previous comments
