### ISSUE TITLE
symfit.Fit with high number of variables

### ISSUE THREAD

**Issue by nykkola** [tBuLi/symfit#122]
Hello,

I am currently performing some global fitting assay on a quite big dataset using symfit. So far everything has been perfect with a defined dictionary of 3 variables, but I am looking for a way to introduce a high number of variables in the Fit function, since writing

'fit=sp.Fit(model_dict, x1=xdata, x2=xdata, ... , x350=xdata , y1=ydata1, y2=ydata2, ... , y350=ydata350)` 

scares me. So far I was not able to find an example showing that, and being a newbie in programming I may have missed it. 

I am using Python 2.7 with symfit 0.3.6

Thanks in advance!

**Comment by pckroon** [comment]
Hi Nykkola,

you can make a dictionary with your keyword arguments: `my_data_kwargs = {'x1': xdata1, 'x2': xdata2, ..., 'x350': xdata350, 'y1': ydata1, ...}`, and you can (and should) of course do that programmatically. Don't go typing this.
You can then call `Fit` as follows: `fit = sp.Fit(model_dict, **my_data_kwargs)`.

I hope this helps!

**Comment by tBuLi** [comment]
Agree with everything said above, The same goes for the creation of your variables:

`xs = variables(','.join(['x{}' for i in range(1, 351)]))`

The only example in the docs of this type is [here](http://symfit.readthedocs.io/en/latest/fitting_types.html#advanced-usage).

I will however close this, as it is not an issue. Please use e.g. http://stackoverflow.com/ for this type of questions. If you tag your question with [curve-fiiting], [python] and/or [symfit], I will probably read it at some point.
