### ISSUE TITLE
Build failed for 0.3.7

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#127]
@pckroon Any idea what blew up here?

https://travis-ci.org/tBuLi/symfit/builds/233138521

**Comment by pckroon** [comment]
It looks like pbr had a hickup. It might've been transient. Alternatively, pbr was update about a month ago (20/4), so maybe they broke something? I can't find anything in their changelog (https://docs.openstack.org/developer/pbr/history.html) though.
Could you try re-triggering the Travis build?

**Comment by tBuLi** [comment]
Fixed with PR #128 by switching back to the previous version of sphynx. Look like they made a change that pbr doesn't like. For now, freezing the sphynx version we use solves the problem.

**Comment by tBuLi** [comment]
This was fixed in #225.
