### ISSUE TITLE
IndexError in symfit 4.0

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#142]
While using jupyter notebook:

```python    
from symfit import Fit, Variable, Parameter, exp
import numpy as np

y_val = 3*np.arange(10) + np.random.rand(10)
x_val = np.arange(10)

a = Parameter(name='a', value=2)
x = Variable(name='x')
y = Variable(name='y')
model = {y: a*x}

fit = Fit(model, y=y_val, x=x_val)
res = fit.execute()
print(res)
```

**symfit 0.4.0 result:**

IndexError                                Traceback (most recent call last)
<ipython-input-9-e13847a5c7c4> in <module>()
      1 fit = Fit(model, y, np.arange(10))
----> 2 fit.execute()

C:\Miniconda3\envs\py3_64bit\lib\site-packages\symfit\core\fit.py in execute(self, **minimize_options)
   1362         else:
   1363             if cov_matrix is None:
-> 1364                 cov_matrix = self.covariance_matrix(dict(zip(self.model.params, minimizer_ans._popt)))
   1365         finally:
   1366             minimizer_ans.covariance_matrix = cov_matrix

C:\Miniconda3\envs\py3_64bit\lib\site-packages\symfit\core\fit.py in covariance_matrix(self, best_fit_params)
    848         if len(set(arr.shape for arr in self.sigma_data.values())) == 1:
    849             # Shapes of all sigma data identical
--> 850             return self._cov_mat_equal_lenghts(best_fit_params=best_fit_params)
    851         else:
    852             return self._cov_mat_unequal_lenghts(best_fit_params=best_fit_params)

C:\Miniconda3\envs\py3_64bit\lib\site-packages\symfit\core\fit.py in _cov_mat_equal_lenghts(self, best_fit_params)
    916         # set to None
    917         mask = [data is not None for data in self.dependent_data.values()]
--> 918         jac = jac[mask]
    919         W = W[mask]
    920 

IndexError: index 1 is out of bounds for axis 0 with size 1

**symfit 0.3.7 result**

Parameter Value        Standard Deviation
a         3.067436e+00 2.632309e-02
Fitting status message: Both actual and predicted relative reductions in the sum of squares
  are at most 0.000000 and the relative error between two consecutive iterates is at 
  most 0.000000
Number of iterations:   3
Regression Coefficient: 0.9975745258778513

**Comment by tBuLi** [comment]
Unfortunately I failed to reproduce this error. These are the packages I used locally to fail the reproduction:

 sympy 1.0
 symfit 0.4.0
 scipy 0.18.1
 numpy 1.14.0
 jupyter 1.0.0
 jupyter-core 4.3.0
 jupyter-console 5.2.0
 jupyter-client 5.1.0
 matplotlib 2.0.0

Can you comment on the versions you used?

**Comment by Jhsmit** [comment]
backports.shutil-get-terminal-size==1.0.0
bokeh==0.11.1
cycler==0.10.0
decorator==4.0.10
entrypoints==0.2.2
funcsigs==1.0.0
ipykernel==4.3.1
ipython==4.2.0
ipython-genutils==0.1.0
ipywidgets==5.1.5
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==4.1.1
jupyter-core==4.1.0
jupyterlab==0.0.10
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
mpmath==0.19
nbconvert==4.2.0
nbformat==4.0.1
notebook==4.2.1
numpy==1.11.0
ordered-set==2.0.1
ordereddict==1.1
pandas==0.18.0
pickleshare==0.7.2
Pillow==3.2.0
plotly==1.10.0
Pygments==2.1.3
PyLaTeX==1.0.0
pyparsing==2.0.3
pyreadline==2.1
python-dateutil==2.5.2
pytz==2016.3
PyYAML==3.11
pyzmq==15.2.0
qtconsole==4.2.1
reportlab==3.3.0
requests==2.10.0
scipy==0.17.0
seaborn==0.7.0
simplegeneric==0.8.1
six==1.10.0
symfit==0.4.0
sympy==1.0
tifffile==0.8.0
tornado==4.3
traitlets==4.2.1
traits==4.5.0
widgetsnbextension==1.2.3

Python 3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by tBuLi** [comment]
Further investigation by @Jhsmit has found that numpy < 1.12.x causes this problem. Since 1.12 was released only on 18 Mar 2017, it might still be necessary to fix this on our end, since a lot of people might still be using older versions.
