### ISSUE TITLE
Vector valued functions

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#15]
In order to allow vector valued functions as models, a nice way to define such functions is needed. Unless I am mistaken, sympy does not have a standard way of doing this (yet?).

What would be the best way of doing this? I propose the following:
- list of functions
```python
a = [x**2, y**2, 2 * x * y]
```
Or a tuple could be used if it makes more sense for it to be immutable.
- vector object
```python
a = vector(x**2, y**2, 2 * x * y)
```
- overload an otherwise unused operator, e.g.
```python
a = x**2 & y**2 & 2 * x * y
```
Other operators that could be used are ```|``` and ```^``` but 'bitwise and' makes more sense to me.

**Comment by tBuLi** [comment]
I have a new proposal.

Perhaps the most self consistent proposal to date, because this syntax ~~is already used~~ will be reintroduced soon for use with constraints:

```python
y1, y2, x = variables('y1, y2, x')
model = [
    y1 == x**2,
    y2 == 2 * x,
]
```

This syntax is backwards compatible with existing code.

Unnamed model:
```python
x = Variable()
model = 2 * x
```

Named model:
```python
y, x = variables('y, x')
model = y == x**2
```

This is also nicely consistent with #30, allowing data to be provided by the name of the variable. In the last example, ```Fit``` would be called as:
```python
model = y == x**2
fit = Fit(model, x=xdata, y=ydata)
```
while in the case of an unnamed model, the ```data``` keyword should be used:
```python
model = 2 * x
fit = Fit(model, x=xdata, data=ydata)
```

**Comment by tBuLi** [comment]
I have decided to give up on overloading == and != because they are to deeply ingrained in sympy. Although I can get it to work in my tests, it doesn't feel save. So instead, I am now thinking of using a slightly more pythonic construct to define vector-valued functions: dicts.

This is also not a bad solution as it is at least consistent t with sympy.

```python
y1, y2, x = variables('y1, y2, x')
model = {
    y1: x**2,
    y2: 2 * x,
}
```

The loss of order in a dict is not a problem for the use cases I am thinking of, but just in case it might be important to some users I'll duck type the whole thing to be compatible with OrderedDicts.

**Comment by Pitje06** [comment]
I like the proposed dictionary syntax, especially if wrapped over multiple lines as shown.
The only concern I have is when using full-fledged functions:

    def f(x, y):
        return x+y, x*y - 1

What would be the elegant way of turning this into a model using the proposed syntax?

**Comment by tBuLi** [comment]
That's a great point. The rationale behind naming the data consists of a couple of points:

### Increased readability ###
I have noticed that in fitting to multidimensional data, in the current form unnecessary stacking is required:

Example:
```python
xdata = np.arange(-5, 5, 1)
ydata = np.arange(-5, 5, 1)
xx, yy = np.meshgrid(xdata, ydata, sparse=False)
xdata_coor = np.dstack((xx, yy))

zdata = (2.5*xx**2 + 3.0*yy**2)

a, b = parameters('a, b')
x, y = variables('x, y')
model = (a*x**2 + b*y**2)

fit = Fit(model, xdata_coor, zdata)
```

Is less readable then the new style

```python
xdata = np.arange(-5, 5, 1)
ydata = np.arange(-5, 5, 1)
xx, yy = np.meshgrid(xdata, ydata, sparse=False)

zdata = 2.5 * xx**2 + 3.0 * yy**2

a, b = parameters('a, b')
x, y = variables('x, y')
model = a * x**2 + b * y**2

fit = Fit(model, x=xx, y=yy, data=zdata)
```

Plus the new form saves you the time in figuring out how to stack the data, which never works the first try.

So if this is a helpful step on the input side, why not do the same for the output? It is also makes the call to fit look more readable:

```python
model = {z: a * x**2 + b * y**2}

fit = Fit(model, x=xx, y=yy, z=zdata)
```

### Internal consistency ###
Internally, the new syntax is just great. If the fit object is handed a dict as model, I can build the chi squared function with a one liner:

```python
chi_squared = sum((y - f)**2/sigmas[y]**2 for y, f in model.items())
```

In this line ``sigmas`` is a defaultdict which contains all vars that where given a value, but returns 1 otherwise. 

This function is then turned into a python function using ```lambdify``` and the values are provided to the variables by using partial. It makes the internal treatment of dependent and independent variables beautiful.

### Naming over ordering ###
Related to readability, naming arguments is way more readable to positional arguments. The same thing holds for your output array. Yes, you may now that the data in the output array is 3xN and that they represent z1, z2, z3, but will you know in a couple of weeks? Will your fellow programmer? numpy structured arrays are better than normal ones because you can call on a column using it's name, e.g. ```data['x']``` instead of ```data[:, 0]```. For the same reason, I prefer 

```python
fit = Fit(model, x=xdata, y=ydata, z_1=zdata[0], z_2=zdata[1], z_3=zdata[2])
```
to 
```python
fit = Fit(model, x=xdata, y=ydata, data=zdata)
```

#### Easier Debugging ####
As a final note, I think this will make users spend less time on debugging, because it's a lot clearer which data ends up where.


I hope this clarifies the rationale. I will also consider yours a bit longer before answering that because a tuple is also unambiguous, although for the reason named above I think it's a lot less readable.
