### ISSUE TITLE
Clarification on Fixing the Value of Parameter

### ISSUE THREAD

**Issue by bhclowers** [tBuLi/symfit#150]
For the following example, I was hoping to get some clarification on the parameter c.  My reading of this syntax is that the value of c should not change through the fitting routine.  However, upon examination of the fit results it appears as though it has, in fact, be altered.  Is there a way to truly fix the value so it doesn't change or am I simply misunderstanding the approach? Currently, I'm using symfit 0.4.0 and python 3.

```
from symfit import parameters, variables, exp, Fit, Parameter

a, b, c, d = parameters('a, b, c, d')
x, y = variables('x, y')

c.value = 4.0
c.fixed = True

model_dict = {y: a * exp(-(x - b)**2 / (2 * c**2)) + d}
fit = Fit(model_dict, x=xdata, y=ydata)
fit_result = fit.execute()
```
The output of the fit_result.params call is and I would expect c to still be 4.0:

```
OrderedDict([('a', 16.374368575343127),
             ('b', 0.49201249437123556),
             ('c', 0.5337962977235504),
             ('d', -9.55593614465743)])
```

Cheers,
Brian

**Comment by pckroon** [comment]
Hi Brian,

That is indeed the expected output. However, I can't reproduce your issue:

```python
from symfit import parameters, variables, exp, Fit

import numpy as np

xdata = np.arange(100)
ydata = np.arange(100)

a, b, c, d = parameters('a, b, c, d')
x, y = variables('x, y')

c.value = 4.0
c.fixed = True

model_dict = {y: a * exp(-(x - b)**2 / (2 * c**2)) + d}
fit = Fit(model_dict, x=xdata, y=ydata)
fit_result = fit.execute()

print(fit_result)
```

```
Parameter Value        Standard Deviation
a         -6.714024e+01 1.147315e+01
b         6.743333e+00 7.826861e-01
c         4.000000e+00 8.516989e-01
d         5.599811e+01 2.655657e+00
Fitting status message: Optimization terminated successfully.
Number of iterations:   24
Regression Coefficient: 0.3309511795685749
```

What's your scipy version? And can you double check the version of symfit you're running?

**Comment by bhclowers** [comment]
Using the `pip show package` command I have tried the example with:
scipy 1.0.1
numpy 1.14.3
symfit 0.4.0

I have tried this with python 2.7 and 3.6.4.  

The answer I get for python 2.7 is (which still isn't correct) but only if I change the variable c to 3.0.  If I leave it at 4.0 I get a `LinAlgError: Singular matrix` exception:
```
Parameter Value        Standard Deviation
a         -6.231973e+04 6.465677e+02
b         -3.759177e+04 3.899764e+02
c         3.779818e+04 3.921493e+02
d         3.800524e+04 3.950286e+02
Fitting status message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
Number of iterations:   84
Regression Coefficient: 0.9999999999914775
```
For python 3.6 I get the following output when c is set to 4.0:

```
Parameter Value        Standard Deviation
a         -6.231973e+04 6.465677e+02
b         -3.759177e+04 3.899764e+02
c         3.779818e+04 3.921493e+02
d         3.800524e+04 3.950286e+02
Fitting status message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
Number of iterations:   84
Regression Coefficient: 0.9999999999914775
```
For clarity, I've tried this on 2 different systems each having both 2.7 and >=3.5 installed. I cannot appear to fix the value.

**Comment by bhclowers** [comment]
Peter,

The versions I am using on the present box that still yields the odd error are:

symfit (0.4.0)
scipy (1.0.1)
six (1.11.0)
numpy (1.14.3)
sympy (1.1.1)

**Comment by pckroon** [comment]
Cheers. I also found the issue: we never actually implemented fixed
parameters in 0.4.0... pr #151 should fix it though.

Peter
