### ISSUE TITLE
`Constraints` should not be a seperate type.

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#154]
`Constraint`'s are fundamentally just `Model`'s and so should not have a seperate role. They were introduced mostly because they should be derived w.r.t. all the parameters of the associated model, not of the constraint itself.

However, at the time of coding this I had forgotten that python is a consenting adults language. So we could just initiate a normal `Model` with the expression of the constraint, and then overwrite its `.params` and `.vars` with those of the associated model.

This does leave the issue of what to do about the two different fundamental types: `Eq` or `GreaterThan`. This could be either set as an attribute on the model, or we track the different types in the calling function (`Fit`).

**Comment by pckroon** [comment]
The advantage of having separate `Constraints` is ease of use on the user side. So if you want to remove the class `Constraint` it should at least be replaced by a convenience function that does what you describe (something like: `add_constraint(model, constraint)`; or even make it a method of `Model`).

**Comment by tBuLi** [comment]
Not sure that it would impact the user, as users already don't interact with `Constraint`'s directly. The API would not change, it would just be that the current list `Fit.constraints` list would now contain `Model`'s rather than `Constraint`'s. Although this list might now change have to into a dict to be able to separate the types of constraint.

I do intend to make a seperate convinience function which will take care of overwriting the .params etc, though I think it should take a list of constraints: `make_constriants(model, constraints)`. This should be separate from the function `lagrange_multipliers(model, constraints)` that is needed to implement #148 as this should return a list of suitably wrapped constraints that can be fed to `SLSQP`, whereas `lagrange_multipliers` should return a single model that can be fed to any optimizer.

**Comment by pckroon** [comment]
Sounds good! Go for it! ;)
