### ISSUE TITLE
SLSQP should accept symfit-style constraints

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#156]
Currently, when using SLSQP directly one has to provide constraints in a sympy facion:

```python
def f(x, a, b):
    return a * x + b

def chi_squared(a, b):
    return np.sum((ydata - f(xdata, a, b))**2)

custom_minimize = SLSQP(
    chi_squared, 
    [a, b], 
    constraints=[{'type': 'eq', 'fun': lambda a, b: a + b - 1}]
)
fit_results = custom_minimize.execute()
```
which is obviously a lot harder then doing
```python
custom_minimize = SLSQP(chi_squared, [a, b], constraints=[Eq(a + b, 1)])
```
(And this is ignoring manually adding the jacobian of the constraint, which will ruin your day even more.)

This syntax should be supported, as constraints normally only concern `Parameter` objects, so why make it complicated?

**Comment by pckroon** [comment]
Looks like a good idea. Is this a problem for SLSQP only?
And yes, *usually* constraints are only between `Parameter` objects, but maybe not always ("my function value needs to be larger than 0"). 
Also related, what does sympy do when you do `a + b == 1`?

**Comment by tBuLi** [comment]
Currently it is SLSQP only, but I agree that it should be added in such a way that it also works for other `ScipyMinimize` children that support constraints.

I just noticed actually that `ScipyMinimize` already has a classmethod `ScipyMinimize.scipy_constraints` for precisely this, which we apparently forgot to plug in for SLSQP while making 0.4.0. So this shouldn't be hard to fix.

I agree with your comment about constraints not always involving just Parameters, but in those cases you can still do the manual labor yourself. And those kinds of constraints do not work in a symbolic context yet, since you would then need to sum over the data points to have it return a scalar and such operations are not currently supported. However, they will be in 1.0.0.

`a + b == 1` in sympy performs a symbolical equality check, and would therefore return `False`. It does not return a `Eq(a + b, 1)` instance. Unfortunate, but not worth hacking. Believe me, I tried ;). You are btw allowed to say `a + b >= 1`, that does return a `Ge(a + b, 1)` object.

**Comment by pckroon** [comment]
Sounds more like ScipyMinimize should call that on all it's constraints on __init__. That way it's dealt with across the board.

Too bad about the sympy equality thing. It makes sense though.
