### ISSUE TITLE
Parameters should be allowed as initial values to ODEModel

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#160]
In relation to [this SO](https://stackoverflow.com/questions/49149241/ode-fitting-with-symfit-for-python-how-to-get-estimations-for-intial-values) question, it might be worth re-investigating how to allow Parameters to be allowed as initial values, e.g.

```python
x0 = Parameter('x0')
ode_model = ODEModel(model_dict, initial={t: 0.0, x: x0, s: 20.0, p: 0.0})
```
A quick scan of the source tells me this should be straightforward, it will require one extra line to dump any Parameters from initial into the list of parameters of the model, and an extra line or two in `__call__` to correctly feed the provided guesses to the ode-solver.

**Comment by pckroon** [comment]
Yes. From a minimization viewpoint this is trivial, but possibly expensive.

**Comment by tBuLi** [comment]
Not my problem ;).
