### ISSUE TITLE
Unknown amount of dependent variables 

### ISSUE THREAD

**Issue by omergra** [tBuLi/symfit#173]
Hi, 
I am trying to use symfit for a global fit problem. 
I have no prior knowledge on the amount of independent variables i have in the problem. 
Creating the model is no problem of course, but the Fit methods requires named variables. 
Is there any solution to that?  

Thanks

**Comment by pckroon** [comment]
Hello!

Good question! Out of curiosity, what kind of thing are you fitting that you don't know the number of *dependent* variables? How can you know what data it corresponds with? For feeding your data to `Fit` you can use `**` dict unpacking:

```python3
x = variables('...')
a, b = parameters('...')
dependent_vars = []
for idx in range(num_dep_vars):
    var = Variable(name='var_{}')
    dependent_vars.append(var)

model = {dv: a*x+b for dv in dependent_vars}
data = {dv.name: data[idx] for (idx, dv) in enumerate(dependent_vars)}
fit = Fit(model, **data)
result = fit.execute()
```

**Comment by omergra** [comment]
Hey, thanks for the response! I will try it!
I'm implementing a method of  finding blood flow velocity in two photon images based on this article: 
https://www.nature.com/articles/srep07341
The key point is that i am fitting data based on the input image i received, and thus my input size may vary. 
Here is a piece of the code
        v_p = parameters(', '.join('v_{}'.format(key) for key in self.data.keys()))
        D_p = parameters(', '.join('D_{}'.format(key) for key in self.data.keys()))
        y0_p = parameters(', '.join('y0_{}'.format(key) for key in self.data.keys()))
        b_p = parameters(', '.join('b_{}'.format(key) for key in self.data.keys()))
        # create variables for symfit
        x = variables('x')[0]
        y_var = variables(', '.join('y_{}'.format(key) for key in self.data.keys()))
        # get fixed & shared params
        dx, a, w2, a2, tau, s, wz2 = self.get_params()
        # create model
        model_dict = {
            y:  exp(-1*(dst*dx-v*(m.cos(a))*x)**2/(w2+0.5*a2+4*d*x)) *
                exp(-x * x * (v * m.sin(a) - dx / tau) * (v * m.sin(a) - dx / tau) / (
                w2 + 0.5 * a2 + a * d * x))
            for y, v, y0, b, d, dst in zip(y_var, v_p, y0_p, b_p, D_p, dist)
            }

**Comment by pckroon** [comment]
Aah, very cool!

`**`dict unpacking will solve your problem then I think.

Good luck, and be sure to ask if you need more help!

**Comment by omergra** [comment]
Thanks for the help.

**Comment by tBuLi** [comment]
Yeah, `**` is definitely the way to go in cases like this.
