### ISSUE TITLE
Fitting a couple of gaussians with SLSQP / LBFGSB

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#184]
I'm trying to fit my data to the sum of a couple (~4) gaussians. So far I've only been able to fit the data using the `DifferentialEvolution` minimizer, local optimizers dont work or if I chain them with differential evolution they ruin the fit.

Here is some code I use for testing:

```python
import matplotlib.pyplot as plt
from symfit import Fit, parameters, Variable, S, exp, Parameter
from symfit.core.fit import Model
from symfit.core.minimizers import *
import numpy as np

guesses_mu = np.array([801.7, 802.4, 804.3, 805.7])
min_bound_mu = np.array([801.2, 802.1, 803.7, 805.16])
max_bound_mu = np.array([802.2, 803.1, 805.2, 806.2])
guesses_sigma = np.array([0.3, 0.25, 0.42, 0.35])
guesses_amp = [400000, 500000, 120000, 60000]

mu_pars = [Parameter('mu_{}'.format(i), value=guess, min=l_bound, max=u_bound) for i, (guess, l_bound, u_bound) in enumerate(zip(guesses_mu, min_bound_mu, max_bound_mu))]
sigma_pars = [Parameter('sigma_{}'.format(i), value=0.3, min=0.1, max=1) for i, guess in enumerate(guesses_sigma)]
amp_pars = [Parameter('a_{}'.format(i), value=guess, min=0.5*guess, max=1.5*guess) for i, guess in enumerate(guesses_amp)]
x = Variable(name='x')

model = sum([amp*exp(-(x-mu)**2 / (2*sigma**2)) for mu, sigma, amp in zip(mu_pars, sigma_pars, amp_pars)])

x = np.linspace(796, 810, num=200)
wts = np.array([0.5]*4 + [0.001]*4 + [0.1]*4)
factor =1 - wts*(np.random.rand(12) - 0.5)

par_dict = {par.name: f*par.value for f, par in zip(factor, temp_model.params)}
par_dict_guess = {par.name: par.value for par in temp_model.params}

y_guess = temp_model(x, **par_dict_guess)[0]
y = temp_model(x, **par_dict)[0]
y_noise = y + 10000*(np.random.rand(len(y)) - 0.5)

fit = Fit(model, x, y_noise, minimizer=DifferentialEvolution)
res = fit.execute()

```
Here is a graph of the data with initial guesses:
![fit_guess](https://user-images.githubusercontent.com/7881506/46734892-ce1c7e00-cc94-11e8-9768-284af293d283.png)

Here is a graph of the data with the fit by differential evolution:

![fit_data](https://user-images.githubusercontent.com/7881506/46734906-da084000-cc94-11e8-83b5-2781e89b6c06.png)

Yeah, I agree, the fit is beautiful. However, I'd like to use local optimizers and chain optimizers on my real-world data instead of generated data, and that doesnt work. 

Here are some errors:

```python
fit = Fit(model, x, y_noise, minimizer=SLSQP)
```
`Fitting status message: Inequality constraints incompatible`

```python
fit = Fit(model, x, y_noise, minimizer=LBFGSB)
```
`Fitting status message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'`

MINPACK does work however so I might stick with that. 

rename the attached .txt file .ipynb for the python notebook
[gaussian_fitting.txt](https://github.com/tBuLi/symfit/files/2464572/gaussian_fitting.txt)

**Comment by tBuLi** [comment]
Thanks for the nice iPython notebook. When I run it, I  indeed get the same problem. BFGS does seem to give a nice result, but that ignores bounds so that might not work for your real data.

From the error messages I do have the impression that the problem is upstream, in which case there is nothing we can do for you. But I will quickly check if the results passed to scipy make sense nonetheless.

**Comment by tBuLi** [comment]
`symfit` passes the correct guesses and bounds to scipy, so this is either a problem with scipy, or the fitting problem is just ill-defined, although it is weird that a method without bounds performs much better than one with.

**Comment by tBuLi** [comment]
p.s. there is nothing wrong with sticking to MINPACK, I guess it survived so long as the industry standard for a reason ;).

**Comment by Jhsmit** [comment]
MINPACK does the job
