### ISSUE TITLE
Pickling problem FitResults

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#188]
As far as I can tell this issue is related to picking FitResults. 

I have a some code where I use multiprocessing and `pool.imap(worker, iterable` do do some work. The worker is: 

```python
def worker(obj, **kwargs):
    res = obj.optimize(**kwargs)
    return res
```
This gives me the following error:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Miniconda3\envs\cc_symfit\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Miniconda3\envs\cc_symfit\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda3\envs\cc_symfit\lib\multiprocessing\pool.py", line 463, in _handle_results
    task = get()
  File "C:\Miniconda3\envs\cc_symfit\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() takes 3 positional arguments but 4 were given

```

When I only return for example the attribute `FitResult.objective_value` everything works fine. Also normal `map()` instead of `pool.imap()` gives no problems.

Head on over to the [ColiCoords](https://github.com/Jhsmit/ColiCoords/blob/f91efbcec23dfde4956887a48cfe58ad36e2b807/colicoords/cell.py#L940) repo to see the full code.

**Comment by pckroon** [comment]
What is the type of `obj` in the example above?

**Comment by Jhsmit** [comment]
its a `colicoords.Cell` object: [Cell](https://github.com/Jhsmit/ColiCoords/blob/cc9f39876bcc990f2e1bf76d7f4e5b83be26d875/colicoords/cell.py#L19)

**Comment by pckroon** [comment]
Ok... so what (kind of) object raises the TypeError? This is kind of hard to trace to symfit code this way.

**Comment by Jhsmit** [comment]
I've traced the problem to the fact that I'm making a subclass from `CallableNumericalModel` with a different init signature.

```python

from symfit import parameters, variables, Fit, Model, CallableNumericalModel
import pickle

xdata = [1.0, 2.0, 3.0, 4.0, 5.0]
ydata = [2.3, 3.3, 4.1, 5.5, 6.7]
yerr = [0.1, 0.1, 0.1, 0.1, 0.1]

a, b = parameters('a, b')
x, y = variables('x, y')

def func(x, a, b):
    return a*x+b

class CustomModel(CallableNumericalModel):
    def __init__(self, arg1, arg2):
        self.arg1 = arg1
        self.arg2 = arg2

        super(CustomModel, self).__init__({y: func}, [x], [a, b])


model = CustomModel(4, 5)
fit = Fit(model, x=xdata, y=ydata, sigma_y=yerr)
res = fit.execute()

with open('tempfile', 'wb') as f:
    pickle.dump(res, f)

with open('tempfile', 'rb') as f:
    new_res = pickle.load(f)

print(new_res)

```
This gives the same kind of error:

```
Traceback (most recent call last):
  File "C:/Users/Smit/PycharmProjects/CC_Playground/dev/symfit/simple_test.py", line 31, in <module>
    new_res = pickle.load(f)
TypeError: __init__() takes 3 positional arguments but 4 were given
```

The issue was caused by the implementation of `__reduce__` in 43b77e26892089a3571d6693e7105c6fe3128712. When I override `__reduce__` on my subclass with the correct init signature the problem goes away.

It might useful at some point in the future to have some kind of 'advanced usage' section in the docs where users are told how to subclass models etc.
