### ISSUE TITLE
MINPACK chi-squared is not in result.objective_value

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#200]
Usually I use `result.objective_value` to get the value for chi-squared. But when I use MINPACK as minimizer this attribute does not exist and I have to get the value in `result.chi_squared`. It would be nice if this was an attribute independent of the minimizer used.

**Comment by pckroon** [comment]
Duplicate of #85.

**Comment by Jhsmit** [comment]
Oops, I did remember vaguely an issue about this but didnt find it via search. Consider this a bump :)
