### ISSUE TITLE
Fitting ode with data not directly linked to an ode variable

### ISSUE THREAD

**Issue by atoum84** [tBuLi/symfit#204]
Hi,

Thank you for your great framework.

I'm trying to use ODE fitting when my data are not directly linked to an ode variable:
+ y : variable of an ode model with some kind of parameters to optimize
+ z_data = f(y,params) 
    where:
            * z_data : my data
            * f is a given function but it's not an ode 
            * params are additionnal parameters to optimize

After some kind of test, I didn't figure out how to do that.

If it's not possible, could you add this features?
If it's possible, could you add the procedure in the documentation because I didn't find the obvious way to do it?

**Comment by tBuLi** [comment]
That's an interesting question, thank you for asking it. It is not yet possible to do this in the most elegant way possible, but there is a good workaround using `CallableNumericalModel`. Let me give a simple example:

```python
y, z = variables('y, z')
a, b = parameters('a, b')

ode_model = ODEModel({D(y, x): - a * y} , initial={y: 1.0})
model = CallableNumericalModel({z: lambda x, a, b: ode_model(x=x, a=a).y + b}, 
                               independent_vars=[x], params=[a, b])
fit = Fit(model, x=xdata, z=zdata)
fit_result = fit.execute()
```
I haven't actually tested this code, but apart from a possible SyntaxError which is left to the reader, this should work.

I will add something like this to the docs in the future, but CallableNumericalModel is very new and still undergoing some changes so maybe not just yet. Let me know if the above workflow indeed solves your problem, if it does than this would definitely make a good advanced use example.

**Comment by atoum84** [comment]
Thanks a lot, it's working.

Here, a simple exemple:
def fun(ode_model):
    def fun_(x, k, k2):
        return 2.0 * ode_model(x=x, k=k).y + k2

    return fun_

x_data = np.linspace(0.0, 10.0, 1000)
k_expected = 0.6
k1_expected = 10.0
y_data = 2 * np.exp(k_expected * x_data) + k1_expected

y, x, z = variables('y, x, z')
k = Parameter('k', 0.0)
k2 = Parameter('k2', 0.0)

ode_model = ODEModel({D(y, x): k * y}, initial={x: 0.0, y: 1.0})
model = CallableNumericalModel({z: fun(ode_model)},independent_vars=[x], params=[k,k2])

fit = Fit(model,x=x_data, z=y_data)
fit_result = fit.execute()

print(fit_result)

**Comment by tBuLi** [comment]
Thank you for the minimal example, I will turn that into an example for the docs if you don't mind. I will leave this issue open for now as a reminder that this should be added to the docs.

**Comment by DuckNrOne** [comment]
How is the status of this issue?

**Comment by tBuLi** [comment]
It is still open, so if you want to take this up that would be very much appreciated!

**Comment by DuckNrOne** [comment]
Then I would get into this.

**Comment by DuckNrOne** [comment]
I already found an example of the [CallableNumericalModel](CallableNumericalModel). I can add this example, but I don't want to repeat me.

**Comment by tBuLi** [comment]
I don't think that's necessarily a bad thing since it's very powerful so it's good to show of the possibilities. Perhaps you can rename the old example to "[Example: Piesewise model using CallableNumericalModel](https://symfit.readthedocs.io/en/stable/examples/ex_CallableNumericalModel.html)", and then this new one as "Example: ODEModels as subproblems using CallableNumericalModel" or something clearer.
