### ISSUE TITLE
Multivariate OdeModel

### ISSUE THREAD

**Issue by atoum84** [tBuLi/symfit#208]
Hello,

I'm trying to solve a simple multivariate OdeModel (in my real application is more complex).
I see in the documentation an exemple for the multivariate Model but not for OdeModel.
I implements a simple exemple but I have an error (cf. Traceback)
Did I implement it in the wrong way?

``````python
x_data = np.random.rand(2, 10)
y_data = np.exp(10 * (x_data[0] + x_data[1]))

y, x0, x1 = variables('y, x0, x1')
k = Parameter('k', 0.0)

model = ODEModel({D(y, x0): k * y, D(y, x1): k * y}, initial={x0: 0.0, x1: 0.0, y: 1.0})

fit = Fit(model, x0=x_data[0], x1=x_data[1], y=y_data)
fit_result = fit.execute()

print(fit_result)
``````

Traceback (most recent call last):
  File "tmp_test.py", line 30, in <module>
    fit = Fit(model, x0=x_data[0],x1=x_data[1], y=y_data)
  File ".conda/envs/mypython3/lib/python3.5/site-packages/symfit/core/support.py", line 355, in wrapped_func
    return func(*bound_args.args, **bound_args.kwargs)
  File ".conda/envs/mypython3/lib/python3.5/site-packages/symfit/core/fit.py", line 1402, in __init__
    super(Fit, self).__init__(model, *ordered_data, **named_data)
  File ".conda/envs/mypython3/lib/python3.5/site-packages/symfit/core/support.py", line 355, in wrapped_func
    return func(*bound_args.args, **bound_args.kwargs)
  File ".conda/envs/mypython3/lib/python3.5/site-packages/symfit/core/fit.py", line 799, in __init__
    signature = inspect_sig.Signature(parameters=parameters)
  File ".conda/envs/mypython3/lib/python3.5/inspect.py", line 2716, in __init__
    raise ValueError(msg)
ValueError: duplicate parameter name: 'y'

**Comment by tBuLi** [comment]
Do I understand correctly that `y(x0, x1)`? Unfortunately that is not supported yet, there can only be one time-like variable for ODEModels. PDEs are not yet supported as such. I'm not familiar with strategies for solving PDEs numerically, but I think you have to rewrite it to a system of ODEs, which we can then plug into symfit.

**Comment by atoum84** [comment]
Yes, y depends of x0 and x1.
I'm not sure it's possible to rewrite it with ODE. Do you have any references?
It would be a great feature to have it. Do you have guidelines to implement it?

**Comment by tBuLi** [comment]
No, unfortunately I have no experience in numerically solving PDEs. But I can give you some pointers on how to go about it in terms of writing something symfit compatible: you can still use [`CallableNumericalModel`](https://symfit.readthedocs.io/en/stable/examples/ex_CallableNumericalModel.html).

For your example above:
```python
x_data = np.random.rand(2, 10)
y_data = np.exp(10 * (x_data[0] + x_data[1]))

y, x0, x1 = variables('y, x0, x1')
k = Parameter('k', 0.0)

def pde_solver(k, x0, x1):
    """This uses some other python modules to solve the PDE"""

model = CallableNumericalModel({y: pde_solver(k=k, x0=x0, x1=x1)}, 
                               params=[k], independent_vars=[x0, x1])

fit = Fit(model, x0=x_data[0], x1=x_data[1], y=y_data)
fit_result = fit.execute()
```

All that's left for you is to write `pde_solver` ;).

**Comment by atoum84** [comment]
Thank you for your answer
