### ISSUE TITLE
model with modulo, round

### ISSUE THREAD

**Issue by bytelinker** [tBuLi/symfit#209]
Hello tBuli,

is it possible to use functions like modulo or np.round in symfit, please? 

model = {y:a * np.round(x,3) + b}
model = {y:a * x%3 + b}

Regards
Bytelinker

**Comment by pckroon** [comment]
`np.round` won't work for sure. Modulo might. Sympy knows the modulo operation, but I don't know whether it's differentiable, which might cause problems. Worth a try though.

**Comment by tBuLi** [comment]
Any valid Sympy expression can be used as a symfit model, but like @pckroon points out, it might not always result in a well behaved model. But have a look at [Mod](https://docs.sympy.org/latest/modules/core.html#sympy.core.mod.Mod), such that your example above changes to 
```python
model = {y:a * Mod(x,3) + b}
```
and let us know if it works.

**Comment by tBuLi** [comment]
I will close this for now because it is not really an issue, but I would be curious to know if this solved your problem so you can always answer here even after closing of the issue.
