### ISSUE TITLE
forced ODE

### ISSUE THREAD

**Issue by vrutten** [tBuLi/symfit#215]
Hi,

Thank you for your great framework.
I am trying to fit a forced ODE (where the forcing occurs at a known time).
e.g.: data in the plot below, where a step input comes at known times.
<img width="631" alt="screenshot 2019-02-10 at 23 18 02" src="https://user-images.githubusercontent.com/15912669/52546168-0d65f300-2d8b-11e9-866c-8f4120771c48.png">

How would you recommend I go about parameterising this?
I tried a few different ways but non would run.

```
y, h, t = variables('y, h, t')
tau, b = parameters('tau, b')
model_dict = {D(y, t): (- y + b + h)/tau} 
```
and then have a CallableNumericalModel?
or
```
y, t = variables('y, t')
tau, b = parameters('tau, b')
model_dict = {D(y, t): (- y + b + h(t))/tau} 
```
where h itself is a function
e.g.:
```
def h(t):
    if t>2 and t<5:
        return 1
    else:
         return 0
```

Thanks for any help - it would really be appreciated.

best,

V

**Comment by pckroon** [comment]
Hi V,

that would probably work :) (read: should)

You'll probably get better results however, if you can come up with continuous form for `h`, for example the product of two steep sigmoids.

```python3
def sigmoid(t, t0=0, k=1, N=1):
    return N/(1+symfit.exp(-k*(t-t0)))

def h(t):
    return sigmoid(t, 2, 100, 1) * (1 - sigmoid(t, 5, 100, 1))
```

Experiment and adjust as needed ;)

**Comment by tBuLi** [comment]
Don't forget that you need to use `ODEModel` in order for the system to be integrated, otherwise indeed it won't run. And I think you could replace `h(x)` by either a `sympy.Piecewise`, or a combination of `sympy.Heaviside`.

**Comment by pckroon** [comment]
> Don't forget that you need to use `ODEModel` in order for the system to be integrated...

Doesn't `Fit` automagically determine there's a derivative in `model_dict`, and just Do The Right Thing (tm)? If not, that's a bug :)

> And I think you could replace `h(x)` by either a `sympy.Piecewise`, or a combination of `sympy.Heaviside`.

I'm still utterly convinced taking a function that is actually derivable makes everything smoother (pun intended). It could very well be that the ODE integrator doesn't like the sudden change either way. IIRC the scipy integrators are fairly intelligent in dealing with steep region by automatically reducing the step size. But that doesn't help for step functions.

**Comment by tBuLi** [comment]
We don't provide that service for `ODEModel`'s I'm afraid. The main reason being that initial values have to provided to `ODEModel` as a mandatory argument, so there is no way to cleanly integrate that into `Fit`. If the OP didn't use `ODEModel`'s, that could explain why the code didn't run.

I agree with you that a smooth function is probably better, though personally I would first try a Piecewise because it is easy.

**Comment by pckroon** [comment]
Good point, I forgot about the initial values. Maybe `Fit` should give a friendly message then?

**Comment by tBuLi** [comment]
I'm closing this issue for now, I'm assuming switching to `ODEModel` did the trick. @vrutten feel free to reopen this issue if it didn't, or report back if this indeed solved your problem.
