### ISSUE TITLE
Default tolerance to Minimizer too low?

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#217]
In `ScipyMinimize` we have the following line:
```python
@keywordonly(tol=1e-9)
def execute(self, bounds=None, jacobian=None, hessian=None, constraints=None, **minimize_options):
```

Why was this choice for `tol` made? In a current fitting problem for my PhD I notice that SLSQP fails to update my initial guess of `0.01` because it is already close enough, whereas NelderMead gives back `1.269...e-2`. Setting `tol=1e-15` makes SLSQP give the same answer. This leads me to think that `1e-9` is probably too low. Why was this value chosen?

**Comment by pckroon** [comment]
Beats me. Does it work better when it's removed?

**Comment by tBuLi** [comment]
Actually no, it seems like our tolerance is more stringent than the default (for most) minimizers, because removing it makes some very simple tests fail in a way that I find unacceptable, like:

```python
AssertionError: 0.09987859400861131 != 0.1 within 7 places
```

So were leaving this where it is ;).
