### ISSUE TITLE
bad operand On fit

### ISSUE THREAD

**Issue by whinis** [tBuLi/symfit#226]
I am attempting to use SymFit to make a more user friendly model for my data and it fits however on attempt to run the model with the fit I get the following error
`
bad operand type for unary -: 'list'`

Here is my model

```
gibbsHelmholtModel=deltaH*(1-(T/Tm))-Cp*((Tm-T)+T*log(T/Tm))

fqcrModel = (thetaN+thetaD*exp(gibbsHelmholtModel))\
	       /(1+exp(gibbsHelmholtModel))```

**Comment by tBuLi** [comment]
Hi @whinis, thanks for reporting your issue. However, it is impossible to answer this question with the information you have provided. Can you provide a minimal example so we can run the code, and include the complete traceback? Thanks!

**Comment by whinis** [comment]
I have changed how I evaluate the model by using 
```
for param in fit.model.params:
		newModel = newModel.subs(param,fit_result.value(param))````
instead of the example in order to graph it. I didn't version the code so I don't have that example anymore

**Comment by tBuLi** [comment]
You can evaluate the model as e.g.
```python
newModel(x=xdata, **fit_results.params)
```
depending on what the dependent variables are, here I assume you called them `x`.

**Comment by whinis** [comment]
Using that is what gave me the bad operand however using subs did not

**Comment by pckroon** [comment]
Until there's a minimum working example we can use to investigate this further there is not much more we can do or say. So I'll close this issue. Feel free to reopen it or continue the conversation if you have further questions.
