### ISSUE TITLE
Remove leastsqbound, use scipy equivalent

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#253]
Rehash of #67: we should really remove leastsqbound.py in favor of the scipy equivalent, since that is peer reviewed whereas our current file hasn't undergone any changes since its creation.

See https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html

Should be a matter of deleting leastsqbound.py and changing all references to the function `leastsqbound` in `symfit.core.minimizers.MINPACK` to `scipy.optimize.least_squares`.

**Comment by tBuLi** [comment]
@DuckNrOne, I think this might be an interesting first step in your quest to increase coverage since this will simply knock out an ill-tested component without adding any new code. But no pressure, if it doesn't have your fancy just have a look at the unit tests, that would already be great.

**Comment by DuckNrOne** [comment]
while A uses multiple Bs, only 2 elements are allowed on scipy. Also, they have to be ordered, but that's not a problem compared to the first one.

**Comment by tBuLi** [comment]
Sorry, could you elaborate on that? I don't understand your comment. What are A and B?

**Comment by DuckNrOne** [comment]
I don't know why I used A and B :D While `leastsqbound` uses multiple boundaries, only 2 elements are allowed on `scipy`. Also, they have to be ordered, but that's not a problem compared to the first one.
