### ISSUE TITLE
0.5.0 on conda-forge

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#257]
So far, I have had no success getting 0.5.0 on conda-forge. The issue seems to be with the 3.7 version of symfit 0.5.0. Personally I will stop my attempts to get it up there, and hope it solves itself with the next release since we did some cleanup to setup.py to include 3.7 as an official version.

In the meantime, if someone more experienced or patient with conda would like to give it a shot, that would of course be much appreciated.

**Comment by Jhsmit** [comment]
fixed: https://github.com/conda-forge/symfit-feedstock/pull/8

**Comment by tBuLi** [comment]
I don't think 0.5.0 is on there, but 0.5.1 is right? I have no problem with that, thanks for getting this fixed!
