### ISSUE TITLE
Is it possible to fit a*x**b + c?

### ISSUE THREAD

**Issue by lesshaste** [tBuLi/symfit#272]
I would like to perform a least-squares fit to a curve.  I tried

```
a, b,c  = parameters('a, b, c')
x = variables('x')
model = a*x**b + c

```

However symfit complains about the exponentiation with

> AttributeError: 'Tuple' object has no attribute '_eval_power'

Is this possible to do in symfit?

**Comment by pckroon** [comment]
Yes, but `variables` returns a tuple (of Variables). Two solutions:
```python
a, b,c  = parameters('a, b, c')
x, = variables('x')  # Note the extra comma
model = a*x**b + c
```
or
```python
x = Variable('x')
```

**Comment by lesshaste** [comment]
Thank you so much.
