### ISSUE TITLE
scipy requirements

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#277]
The current scipy requirement for symfit ``0.5.1`` is ``scipy >= 1.0, <1.2``, which could cause ``conda`` to install symfit ``0.4.6`` when the user has scipy >= 1.2 installed since it has more lenient requirements of only ``scipy >= 1.0``.

Is the current version of symfit really incompatible with say scipy 1.3? Checking / fixing this would allow conda to distribute more the most recent version and thereby prevent bugs.
See also: https://stackoverflow.com/questions/58341121/global-fitting-with-symfit-typestructure-of-dataset/

Also, personally I like to use the new ``workers`` kwargs for DifferentialEvolution which is available from scipy v1.2.

**Comment by pckroon** [comment]
On master with scipy==1.3.1 all tests pass. I have no clue about conda though. Maybe you could open a PR to fix this? :)

**Comment by Jhsmit** [comment]
yeah, I can have look at some point. What I remember is that there where (for my applications) some (temporal) performance issues with scipy >1.2

**Comment by ocefpaf** [comment]
> I have no clue about conda though. Maybe you could open a PR to fix this? :)

`conda` and other downstream packagers are only following what is specified in https://github.com/tBuLi/symfit/blob/master/requirements.txt#L2, and that `is scipy >= 1.0, <1.2`.

**Comment by Jhsmit** [comment]
Scipy <1.2 is not compatible with python 3.8. I'll do some testing next week but since  #283 runs without a problem on python 3.8 without this constraint I dont think there is any issue. I remember that in my applications the scipy >1.2 versions had some performance issues but I'll see if that is still the case

**Comment by Jhsmit** [comment]
I've tested my applications of ``symfit`` with ``scipy == 1.1.0`` and ``scipy == 1.3.1`` and didnt find any noticable difference.
