### ISSUE TITLE
master tests fail on HadamardProduct

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#297]
The ``HadamardProduct`` in ``test_constrained`` raises an error:

```
NameError: name 'HadamardPower' is not defined
```
It seems like somewhere Power and Product got mixed up?

Might be related to
https://github.com/sympy/sympy/issues/17138

**Comment by tBuLi** [comment]
It was due to HadamardPower being added in sympy 1.5, which was not printed yet. I solved it now in #300. 

As a tip to you, I think you should rebase all your PR's on the current master to get better testing, or alternatively merge master into it.
