### ISSUE TITLE
Minimizer Switch NameError: name 'NelderMead' is not defined

### ISSUE THREAD

**Issue by richardgalt** [tBuLi/symfit#302]
Trying to switch minimizes throws the following error.  NameError: name 'NelderMead' is not defined.

`
from symfit import parameters, variables, Fit, Model
import numpy as np

xdata = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
ydata = np.array([2.3, 3.3, 4.1, 5.5, 6.7])
yerr = np.array([0.1, 0.1, 0.1, 0.1, 0.1])

a, b = parameters('a, b')
x, y = variables('x, y')
model = Model({y: a * x + b})

fit = Fit(model, x=xdata, y=ydata, sigma_y=yerr, minimizer=[NelderMead, BFGS])
fit_result = fit.execute()
print(fit_result)
`

**Comment by Jhsmit** [comment]
try importing them by adding:
```python
from symfit.core.minimizers import *
```
