### ISSUE TITLE
TrustConstr cannot handle LogLikelihood with constraints

### ISSUE THREAD

**Issue by DuckNrOne** [tBuLi/symfit#305]
An error was pointed out when translating [`test_fit_result`](https://github.com/tBuLi/symfit/blob/master/tests/test_fit_result.py) in #289 :
In the case, that you want to fit a model with constraints and the minimizer `TrustConstr` with the objective `LogLikelihood`, you get an [error message](https://travis-ci.org/github/tBuLi/symfit/jobs/704984071#L1486) regarding a missing Hessian.

The corresponding code was approximately the following:
```python
def ge_constraint(a): 
    return a - 1

model=Model({y: a * x ** b})
constraints = [
    Eq(a, b),
    CallableNumericalModel.as_constraint(
        {z: ge_constraint}, connectivity_mapping={z: {a}},
        constraint_type=Ge, model=model
    )
]
fit = Fit(model, x=np.linspace(1, 10, 10), minimizer=TrustConstr, objective=LogLikelihood, constraints=constraints)
result = fit.execute()
```

**Comment by tBuLi** [comment]
What is `ge_constraint` here? I have the feeling it is not so much because it doesn't support a constraint, but constraints of the type CallableNumericalModel since they don't have a Jacobian/hessian and TrustConstr requires this.

**Comment by DuckNrOne** [comment]
`ge_constraint` is a method I forgot to mention.

**Comment by tBuLi** [comment]
Yeah I think it is most probably because of CallableNumericalModel not having jacobians or hessians, which is actually expected behavior.
