### ISSUE TITLE
Are there plans for a new release in the near future as 0.5.2 has restrictive SciPy requirements that have been removed in `master`

### ISSUE THREAD

**Issue by brocksam** [tBuLi/symfit#314]
0.5.2 has the requirement of 1.0<=SciPy<1.2 which I'm finding is restrictive on certain projects that want to use Symfit in addition to SciPy>=1.2. As it's been a while since the 0.5.2 release, since which a number of PRs have been merged in to Symfit's `master` branch including one which updates the SciPy requirement to be SciPy>=1.2, would it be possible to have a 0.5.3 release (available via pip on PyPI and conda on conda-forge as usual)? Thanks!

**Comment by tBuLi** [comment]
Hi @brocksam, excellent suggestion. I've been laboring under the false impression that this was already fixed but apparently it wasn't released yet. I've added it to my todo list, should happen soon!

**Comment by brocksam** [comment]
Great news, thanks! Please let me know if I can do anything to help!

**Comment by tBuLi** [comment]
Alright, it is released and on PyPI. Now lets wait for the anaconda bot to notice.

**Comment by Jhsmit** [comment]
Currently the problem on conda forge is the `pkg_resources` dependency, which is not available on conda forge. I'd say switch to `pbr`

**Comment by tBuLi** [comment]
I’m not sure I understand. I saw in your new PR to include pkg_resources in the requirements, so I take it that’s a good thing? And we already use pbr.

**Comment by Jhsmit** [comment]
Yes sorry for the confusion, I made that PR before realizing ``pkg_resources`` wasnt on conda-forge

We use ``pbr`` in ``setup.py``, but not in the code itself. I'm proposing to substitute ``pbr`` for ``pkg_resources`` there

**Comment by Jhsmit** [comment]
arrgh. ``pbr`` has ``pkg_resources`` as a dependency which works because ``pkg_resources`` seems to be a module of ``setuptools``. I"ll try that.

**Comment by Jhsmit** [comment]
Ok, that fixed it, the 0.5.3 should be on conda-forge shortly. 
I've updated my PR to include setuptools: https://github.com/tBuLi/symfit/pull/316
setuptools is preinstalled in new conda envs so this missing dependency never caused any problems conda users

**Comment by pckroon** [comment]
Tangential question, why do we need the conda release?
Symfit is pure python, so I don't really see the added benefit of *also* maintaining a conda-forge release, especially considering its apparent idiosyncrasies. Can't conda diehards do `conda install scipy matplotlib; pip install symfit`?

**Comment by brocksam** [comment]
> Tangential question, why do we need the conda release?
> Symfit is pure python, so I don't really see the added benefit of _also_ maintaining a conda-forge release, especially considering its apparent idiosyncrasies. Can't conda diehards do `conda install scipy matplotlib; pip install symfit`?

If a project has a dependency on Symfit and wants/needs to be on conda-forge then Symfit is required to be on conda-forge also (see [point 6 in the conda-forge/staged-recipes README](https://github.com/conda-forge/staged-recipes)). Additionally, if one's using a conda virtual environment and installing some packages using conda and some using pip, then when updating packages within that environment it's much more liable to break as pip has a much tougher job of resolving package dependencies than conda. Hope that makes sense! From a personal perspective, I need Symfit on conda-forge for a number of projects I develop and maintain.

**Comment by brocksam** [comment]
> I don't know why conda doesn't pick up on the setup requirements we list in setup.py though?

They've now got a tool that attempts to do this as part of the build process. But it's very hit and miss at the moment. They're working on it but it's definitely not reliable yet!

**Comment by tBuLi** [comment]
Closing as 0.5.3 is now on both PyPI and conda, thanks for the reminder @brocksam!
