### ISSUE TITLE
pip installing symfit fails to install sympy

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#32]
perhaps in setup.py 'install_requires' should be changed to 'requires'? 
not tested

**Comment by Pitje06** [comment]
install_requires seems to be correct. For setuptools rather than distutils, that is.
Converting might be worthwhile, especially considering the trouble installing this from pypi using pip. IIRC it installs an older version.

**Comment by tBuLi** [comment]
Changed it to setuptools. 

On which OS are you? I remember experiencing difficulties pip installing scipy directly as well.

**Comment by Pitje06** [comment]
Ubuntu 14.04 x64
pip 1.5.6 from /usr/local/lib/python3.4/dist-packages/pip-1.5.6-py3.4.egg (python 3.4)

**Comment by Pitje06** [comment]
Resolved, should be closed.
