### ISSUE TITLE
Example not works

### ISSUE THREAD

**Issue by nfhktwrbq** [tBuLi/symfit#346]
Example [Fit (Least Squares)](https://symfit.readthedocs.io/en/stable/fitting_types.html#fit-least-squares)
fails with error:
`
model = a * x + b
TypeError: can't multiply sequence by non-int of type 'Parameter'
`

Python 3.8. Symfit 0.5.3

**Comment by pckroon** [comment]
Small typo in the example: use `x, = variables('x')` instead.
