### ISSUE TITLE
Make model calls consistent

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#39]
Currently there are a couple of equivalent functions in `Model` and expr that do roughly the same. I should check to make sure that there is no overlap in their tasks. How I think it should work:

`Expr.__call__` evaluates a sympy `Expr` with given args and kwargs.
`Model.__call__` should evaluate each of the `Expr` in `model_dict`.
`Model.numerical_components` is thereby redundant and should be removed. There should be only one obvious way, and thats to call `Model`.

**Comment by pckroon** [comment]
I would like the jacobian methods to this list. There are a few of them, and they do more or less the same thing, but differently, and it's not immediately clear from their names. There should be a clear distinction between methods that use the symbolic information (and are fast/cheap) and those that use numerical approximations (and are slow/expensive).

**Comment by tBuLi** [comment]
This has by now been solved: models should be evaluated by calling them, but the lambdafied functions are stored in `numerical_components`. Additionally, jacobians and hessians are now seperate models which are available under `model.jacobian_model` and `model.hessian_model`. This structure allows for a lot more efficient code reuse.
