### ISSUE TITLE
fit.data should have dependent vars as keys (?)

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#41]
`fit.data` and it's derivatives currently have Variable names as key, np.array as data. To make the internal API cleaner, it should be considered to change this to Variable: np.array pairs. This will make the code in certain other methods cleaner, since you often encounter things like this: (`self` is a `Fit` instance)

``` python
{var.name: self.data[var.name] for var in self.model.dependent_vars}
```

Could be sexyfied into

``` python
{var: self.data[var] for var in self.model.dependent_vars}
```

Since I don't think it more convenient to use the name anywhere except when initiating `data`.

**Comment by Pitje06** [comment]
I agree that this should be unified, one way or the other.
Currently, it looks like `Fit` consistently uses names, and `Fit.model` uses objects.

**Comment by tBuLi** [comment]
Additionally, in support now lives a function called `key2str`. You give it a dict, and it changes the keys of that dict to strings. In the example above,

```python
dependent_data = {var: self.data[var] for var in self.model.dependent_vars}
model(**key2str(dependent_data))
```
This means that such dicts can still be used to evaluate functions with relative ease, while making all other code _way_ better.

**Comment by tBuLi** [comment]
Was closed with https://github.com/tBuLi/symfit/commit/bc10044230e9817d0c85ed8df49d243b7c73e8f3
