### ISSUE TITLE
Reorganise tests

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#44]
Tests should be restructured over multiple files depending on the thing they test, because the current test object has become to big.

**Comment by Pitje06** [comment]
Read the following; it's mostly on test driven development, but particularly the last one has some nice pointers on organizing test cases.

http://docs.python-guide.org/en/latest/writing/tests/
http://www.onlamp.com/pub/a/python/2004/12/02/tdd_pyunit.html (optional)
http://onlamp.com/pub/a/python/2005/02/03/tdd_pyunit2.html

Another thing that irks me with the current tests is that they print text all over the place (fit results, numpy warnings, some random numbers). Either way, I think that the test cases need to be cleaned considerably, also cutting out unused imports and variables.

**Comment by pckroon** [comment]
I think this is fixed.
