### ISSUE TITLE
Fitting to an ODE as model

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#48]
I would really like to be able to fit to differential equations. This problem recently came up while helping a friend with his data.

This thread is meant to be a brainstorm about potential syntaxes as well as the implementation.

```python
p, q, r = parameters('p, q, r')
x, y, t = variables('x, y, t')

model_dict = {
    Derivative(x, t): x + p * y,
    Derivative(y, t): q * y + r * x,
}

Fit(model_dict, t=tdata, x=xdata, y=ydata)
```

This uses the existing Derivative object from ``sympy``.

Internally, I think it would be awesome if an ``ODEModel`` could be defined, which takes any (set of) differential equations and integrates them internally. Then a call to this model will return the values of the solutions at the given point and basically behaves as it's solution.

When no exact solution can be found a numerical integration should be performed. Therefore, initial conditions and range should be optional parameters. Some ideas on a syntax:

```python
ODEModel(model_dict, initial=({t: 0, y: 0}, {t: 0, x: 0}), range=(t, 0, 25))
ODEModel(model_dict, initial={y[0] = 0, x[0] = 0}, range=(t, 0, 25))
```
(Although the range can be taken from ``tdata``)

A good syntax for initial conditions is crucial, including the derivatives.

As I currently understand the way to do this, the steps are to first integrate the ODE using the initial guesses for the parameters. Then you fit this to the data, redoing the integration every time you vary the parameters. This is a very expensive process. So I think a good ODE solver is one that can leave the parameters symbolical while integrating numerically by parts such that the integration doesn't have to be repeated when doing the fitting. I have no idea if this is possible, just thinking out loud here.

The integration technique recommended to me was Runge-Kutta: http://mathworld.wolfram.com/Runge-KuttaMethod.html, but I'm not sure yet wether this meets this requirement. As I continue to learn more about this, I will report back here.

**Comment by Pitje06** [comment]
I would approach this in a broader setting: How to deal with functions that are differentiable.
In this setting that would mean you have  a function `f(x, y, t, p, q, r)` that returns a value for the given variables and parameters. Evaluating this function is rather expensive, since it involves calculating this integral (but that't not necessarily bad).

The only question then is how SymFit handles functions for which you can't determine the Jacobian, which should be "simple" numerical fitting (i.e. numerically minimizing the residuals as a function of the parameters). There are a LOT of numerical minimization algorithms available; some require a derivative, others don't. Also see the `method`s of https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.optimize.minimize.html. AFAIK the only method there that does not need a derivative is Nelder-Mead. All others approximate it by evaluating `f` on a LOT of points (particularly bad for high dimensional data). A good initial guess is VERY important here, since convergence will not be great.

As for the numerical integration, a simple trapezoid sum with a small enough dt should be good enough I think.

**Comment by tBuLi** [comment]
I think you make a good point, but I'm unsure how much broader this setting actually is. The way I see it, continuous functions can be defined in one of the following two ways:
- Explicit: a function whose form can be given in elementary mathematical functions. This category is covered.
- Implicit: The function is implicitly defined by an ODE or PDE. In the case of ODE's they are given by ``d(x_i)/dt = f(t, x_1, ..., x_n; p_1, ..., p_n)``. Here ``x_i`` is the function of interest that in general cannot be solved explicitly. (Higher order linear ODE's can typically be rewritten into a system of first order ODE's I think but I'm not sure of the conditions on this)

Both these classes can be defined symbolically. So all that has to be done is to categorize whether model is implicit or explicit and then to integrate in the case of an implicit model.

Actually, since the right hand side of the ODE is explicit and of the form ``f(t, x_1, ..., x_n; p_1, ..., p_n)``, it's jacobian can be determined easily so therefore any solver that wants the jacobian can be used.

So this leaves me wondering which cases have not been handled once first order ODE's are supported:

- higher order non-linear ODE's? How does one go about solving these?
- PDE's, but the same syntax would allow for their implementation and they are still of a form which can be expressed symbolically.
- piece-wise continuous functions. If sympy support these the existing infrastructure should be able to deal with them if I didn't cock up duck-typing anywhere.
- Programmed functions. I still want to implement a ``RawModel`` at some point, for which you define it's callable and derivative as python functions rather than symbolic functions. This should then allow you to tie in custom functions of all kinds with the symfit infrastructure. (at your own risk)

**Comment by Pitje06** [comment]
Counter question: is it worth the effort to treat (systems of) differential equations different from 'programmed functions'? I personally seriously doubt it.

**Comment by tBuLi** [comment]
Programmed functions would still fall in one the above categories; implicit or explicit. After making this distinction they should still be treated in the same way as their symbolic counterparts.

And don't get me wrong, a model is a model is a model. The whole point of symfit is that for every one of these models you can just evaluate it at the points you desire, without having to care whether some integration has to be done in the background. So in that sense nothing is distinguished or treated differently. But of course internally they are different, so this has to be accounted for.

As an extra note, programmed functions are something I want to actively discourage. I see it as a slippery slope to writing the same unreadable mess you see in other libraries. However over the summer I encountered a model which was not writable as a symbolic function so I ended up using ROOT to solve it. For such cases it might be nice have this capability, but I'm already afraid people are going to use it for everything if the capability exists, which is very undesirable.

**Comment by Pitje06** [comment]
I fail to see how programmed functions (as you call them) have to be either implicit or explicit. I can come up with some *nasty* function that does some, e.g. thresholding in a specific range.

As for discouraging these kind of functions, I agree. although if you do it in SymFit (read: use symfit as a scipy wrapper) at least the API will be less horrid.

**Comment by tBuLi** [comment]
Well unless we're talking about two different things, a programmed function such as that will still have a well defined action on the domain.

For example a hard threshold like you suggest might give 1 or 0 depending on the input. But that is still well defined, so no integration required. Only in cases where the function you specify is in some way the derivative of some function you don't know explicitly do you have to integrate, correct?

**Comment by Pitje06** [comment]
It could be that I am missing something fundamental here.
A function F is well defined (deterministic) in it's behaviour:
`F(x1, x2, ..., xm; p1, p2, ..., po) -> Rn`
(How does math work in markdown? `F` maps variables `X` to an n-dimensional vector of real numbers)
But it may not be possible to express `F` using symbolic math easily (there might even be examples where this isn't possible at all), so it will not be possible to differentiate `F` symbolically.
In this frame of mind, it doesn't matter whether you have an ODE or something else; you define `F` which does the integration, normalization, and whatever more so that it maps `X` to `Rn`.
So in essence, I fail to see why ODE's are special snowflakes.

side-note: what do you call "well defined"?

**Comment by tBuLi** [comment]
You are right, we always want some ``F(x1, x2, ..., xm; p1, p2, ..., po) -> R^n`` which has to be defined. The main difference for a system of ODE's is that F has to be build from ``d(x_i)/dt = f(t, x_1, ..., x_n; p_1, ..., p_n)`` in the case of a symbolic ODE, which means a generic way has to be found to build ``F``. Once this has been done every F is the same, which is what I meant with a model is a model is a model.

When you specify your own ``F`` from python code (programmed function) you can do whatever floats your boat. What makes ODE's special is that we would like to have the syntactic sugar since most of them can be written symbolically.

Of course it would be nice if a nice integrator API can be defined so you can reuse that for programmed functions.

"well defined" for me has a very loose definition which is best interpreted as 'whatever works in the current context'. I'm a physicist after all ;).

And github markdown doesn't support any kind of math mode, which was a disappointment for me too. Apparently it's due to safety considerations since you won't be surprised to hear that running latex introduces some security issues.

**Comment by tBuLi** [comment]
This discussion makes a good point, a clear definition of Model is needed, as well some ABC's. See #49.

**Comment by tBuLi** [comment]
A first working model has been implemented to see if this syntax works. And I have to say; it's sexy as fuck. As an example a set of reaction kinetic equations I'm helping a friend with:

```python
a, b, c, d, t = variables('a, b, c, d, t')
k, p, l, m = parameters('k, p, l, m')

a0 = 10
b = a0 - d + a

model_dict = {
    Derivative(d, t): l * c * b - m * d,
    Derivative(c, t): k * a * b - p * c - l * c * b + m * d,
    Derivative(a, t): - k * a * b + p * c,
}

ode_model = ODEModel(model_dict, initial={t: 0.0, a: a0, c: 0.0, d: 0.0}, dt=.001)

# Generate some data
tdata = np.linspace(0, 3, 1000)

# Lazy evaluation ftw, this is where the actual integration is performed.
AA, AAB, BAAB = ode_model(t=tdata, k=0.1, l=0.2, m=.3, p=0.3)

plt.plot(tdata, AA, color='red', label='[AA]')
plt.plot(tdata, AAB, color='blue', label='[AAB]')
plt.plot(tdata, BAAB, color='green', label='[BAAB]')
plt.plot(tdata, AA + AAB + BAAB, color='black', label='total')
plt.legend()
plt.show()
```
![damn sexy](https://cloud.githubusercontent.com/assets/2188968/12431260/c573a216-bef4-11e5-87bd-ec3b356c461b.png)


Fitting to this will be trivial. And since vector valued functions are fitable, you can immediately fit to all three equations at the same time!

```python
Fit(ode_model, t=tdata, a=adata, c=cdata, d=ddata)
```

I could not have planned this better.

**Comment by Pitje06** [comment]
Sorry for the late reply.
I like the syntax. A lot. Also, you convinced me that ODE's are special snowflakes.
I just wonder if you couldn't have done something like this:

```python
model_dict = {
    d: Integrate(l * c * b - m * d, t),
    ...
}
```
This would have the advantage that it makes your model again not specifically an ODE model. But I have a nagging feeling that this would unearth more problems serious problem than introducing an `ODEModel`.

Also, your reaction kinetics look sane, so I think it's working ;)

**Comment by tBuLi** [comment]
Purely from the principle of least surprise, I think it's sensible to define ODEs in the same way that you would write them. Maybe in the future we run into a situation (Integro-differential equations) where Integrate might be the more sensible way of defining things but since I don't think the two syntaxes will be in conflict we'll cross that bridge when we have too ;).
