### ISSUE TITLE
Piesewise continous function fitting

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#54]
Fitting to piecewise functions is quite common. Luckely, most of the code seems to work already, thanks to sympy! The thing that doesn't work yet is the fitting...

Interesting example:
http://stackoverflow.com/questions/35795341/fitting-a-two-layer-model-to-wind-profile-data-in-python#comment60105265_35795341

`symfit` implementation of the solution:

``` python
k, z0, ust, a, b, zsl = parameters('k, z0, ust, a, b, zsl')
z, = variables('z')

model = Piecewise(
    (ust/k * ln(z/z0), z < zsl),
    (a*z + b, z >= zsl),
)

xdata = np.linspace(0, 10)
y = model(xdata, k=0.4, zsl=2., ust=0.3, z0=0.002, a=0.1, b=10.)

fit = Fit(model, xdata, y)
fit_result = fit.execute()
```

It's pretty awesome that the `Piecewise` object is now behaving exactly as one would expect! However, there is one problem: 
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

I think this is caused by the lines like `z < zsl`, which when converted to numpy code will be of the form `np.array < float`. So one possible solution could be to find a way to convert the parameter values to arrays upon calling s.t. the comparison can be made elementwise.

**Comment by Pitje06** [comment]
`np.array < float` is perfectly fine, that gives an `np.array` with datatype `bool`. The problem is calling `bool(np.array)` (implictely).

**Comment by tBuLi** [comment]
Your right, thanks for that correction. The line
```python
y = model(xdata, k=0.4, zsl=2., ust=0.3, z0=0.002, a=0.1, b=10.)
```
already fails with this error (in ```__call__```). So the search is on: somewhere in lambdafying this model a call of the type you suggested is made but I can't see where yet.

**Comment by tBuLi** [comment]
The following MWE could be good to investigate as well: http://stackoverflow.com/questions/41641880/using-scipy-curve-fit-with-piecewise-function.

**Comment by tBuLi** [comment]
Works by now, at least my second example. The first one just seems to be caused at least in part by having a badly behaved model. So symfit is fine!
