### ISSUE TITLE
DOI number for symfit

### ISSUE THREAD

**Issue by pckroon** [tBuLi/symfit#56]
It should be possible to easily cite symfit in academic material, so it should have an DOI number. Luckily, this shouldn't be to hard according to https://guides.github.com/activities/citable-code/.

**Comment by tex-downey** [comment]
I agree, I have cited the documentation page but a DOI would be nice. This should be a simple process for one of the main contributors.

**Comment by tBuLi** [comment]
You are right, I have started setting everything up. In principle the next release should trigger the creation of a DOI, so stay tuned!

**Comment by pckroon** [comment]
Is there an ETA for 0.4.0?
