### ISSUE TITLE
reportlab breaks symfit

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#58]
```
from reportlab.platypus.tables import Table
from symfit.api import Fit, Parameter, Variable
```

results in 
`NameError: name 'long' is not defined`

**Comment by tBuLi** [comment]
Literally just those two lines or is there some extra code there? Which line gives this error?

**Comment by zunzun** [comment]
This is a possible resolution for the namespacing.  You might try:

import reportlab.platypus.tables.Table
rlTable = reportlab.platypus.tables.Table

and then use rlTable (for Report Lab Table) in your code instead of the name "Table"

**Comment by tBuLi** [comment]
@Jhsmit Is this still an issue? I remember you telling me it was also solved by changing the order of the imports?

**Comment by Jhsmit** [comment]
its fixed by changing the order of imports

J. H. Smit, Msc.
Molecular Microscopy Research Group / SMB
Zernike Institute for Advanced Materials
University of Groningen
Nijenborgh 4, 9747 AG Groningen, The Netherlands
--
Office 5114.0103
Phone: +31-(0)-50-363-5705
www.molecular-microscopy.nl
