### ISSUE TITLE
Passing unicode name kwargs in python2 causese mysterious bugs

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#59]
in class Argument changing this:

    if not name or type(name) != str

to: 

    if not name or (type(name) == unicode or type(name) == str):

fixes this bug for python 2.x but no unicode object exists in python 3. Adding

    from past.builtins import basestring
    if not name or (isinstance(name, basestring):

but that adds another dependency.

**Comment by tBuLi** [comment]
After googling a bit I settled on the following solution:

```python
try:
    basestring
except NameError:
    basestring = str
```

Thanks for finding this one!

**Comment by Pitje06** [comment]
See also http://python-future.org/compatible_idioms.html#strings-and-bytes
`from __future__ import unicode_literals` might also do what you want.
