### ISSUE TITLE
Scipy 0.17 supports bounds on parameters

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#67]
Scipy now supports bounds on parameters!

A comparison should be made with the package now used to see if we should switch to using this instead of `leastsqbound`.

http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares

**Comment by Pitje06** [comment]
Keeping #75 and #86 in mind, it may be a better idea to move to a complete refactoring of the code, such that Fit objects are subclasses of an Objective and an Optimize (Minimize or Maximize). This would grant enormous flexibility, but is quite some work to realise.

**Comment by tBuLi** [comment]
Irrelevant with 0.4.0
