### ISSUE TITLE
Regression coefficient mayhem

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#72]
The place in the code where the regression coefficient is calculated switches with every version of `symfit`, because it's hard to define where it belongs.

At the core of this discussion is: should the `FitResults` object also hold all the residuals and data? If so, R^2 and also the reduced chi-squared etc. could be calculated on the FitResults object. However, I'm not sure about this because I don't think the data is a fit result, and also the model isn't, and hence these _goodness of fit_ qualifiers can't be calculated on the FitResults object.

Be that as it may, a unified interface is needed such that we don't have to reinvent how to calculate all this stuff from every `.execute` function on a fitting object. 

So perhaps a set of functions, one for each _goodness of fit_ estimator, that can be used ad lib.

Also, since R^2 is not defined for a vector valued function (I believe) this should be triple checked. It's odd that apparently for a global fit R^2 _is_ defined, yet I've read that for vector valued functions it isn't, even though mathematically the two appear the same in how chi^2 is computed.

**Comment by Pitje06** [comment]
Hmmm... tough cookie.
In a strict sense I'd say the R^2 is a function of the model, the found/proposed parameters, and the data.

So maybe there should be a (global) function that takes all three, and returns the associated number. FitResults should then do the thing that is right in 99% of the cases, which is use that function with the model you used, the parameters you found, and the data you used to find those parameters.
The one user that needs it can then work around edge cases using the r_squared function providing all three arguments by hand.

**Comment by pckroon** [comment]
Referencing #85
