### ISSUE TITLE
Travis-CI

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#73]
This looks pretty amazing. Apparently this app automatically runs tests upon pushing a change, and can also auto compile pip wheels. If true this could remove a lot of the manual labor I've been doing.

https://travis-ci.org

**Comment by Pitje06** [comment]
I've seen it been used for some larger projects, I think it should just work (TM).

**Comment by Pitje06** [comment]
@jbarnoud has experience with Travis, and is willing to look at it. I suggest assigning this to him :)

**Comment by jbarnoud** [comment]
It is on my TODO list.

**Comment by tBuLi** [comment]
I could use an extra pair of eyes on my `deploy-fix` branch. It seems to be very close to auto-deploying on testpypi.python.org, except for a rather annoying bug in the [travis build](https://travis-ci.org/tBuLi/symfit/jobs/175760177):
```
line 491: sh: 1: twine: not found
```
Even though it should be auto installed and appears to have been in the build log. I therefore added the lines 
```
before_deploy:
  pip install twine
```
as suggested [here](https://github.com/travis-ci/dpl/issues/299) to make sure but that did not solve it. (And that issue seems closed with dpl 1.7.19 and we get 1.8.24 by now.) 

Any ideas? I could still try `--user` on the install or `edge: true`, though neither should be necessary anymore according to [299](https://github.com/travis-ci/dpl/issues/299). I am hesitant to keep making minor fixes on the branch but I can't run travis locally on my very old mac. Does any of you see something that I missed?

Btw, I purposely did not make a pull request for this branch, because travis skips the deploy step for PRs. So unfortunately that is not an option in this case.

p.s. it tries to deploy to test for any commit, and to live pypi only for a tagged commit. So line 508 in the build log doesn't mean anything for the deploy to test.

**Comment by jbarnoud** [comment]
Maybe $PATH needs to be updated?

**Comment by Pitje06** [comment]
https://github.com/travis-ci/dpl/issues/296
Maybe try putting the `pip install twine` in the install section.

**Comment by Pitje06** [comment]
As an aside, I'm also in favor of moving to pip instead of conda (because that does magic travis caching), but https://github.com/travis-ci/travis-ci/issues/2650 might be an issue.

**Comment by tBuLi** [comment]
Putting `pip install twine` in the `install` section made [no difference](https://travis-ci.org/tBuLi/symfit/jobs/176377625). 

I am not comfortable enough with $PATH to know how to approach that.

**Comment by jbarnoud** [comment]
My guess, but I could be wrong, is that twine is not in the search path; 
therefore it is not found. One way to test that hypothesis would be to 
print the search path by having `echo $PATH` somewhere. I would have it 
just after the twine install. The $PATH environment variable is a list 
of path separated by columns. If I am right, twine will not be in any of 
the directories listed there; then the path to the directory containing 
twine can be added with `export PATH=directory_to_add:$PATH`.

**Comment by Pitje06** [comment]
Is pip in the same virtualenv that conda created? (Shouldn't matter, but hey)
Maybe try adding twine to 
```
conda create \
    --yes -q -n pyenv \
    python=$TRAVIS_PYTHON_VERSION \
    numpy scipy sympy matplotlib seaborn nose twine
```
?

Otherwise I'm stumped, and blame Travis.

**Comment by jbarnoud** [comment]
Could be worth the try indeed. But yes, pip and conda work in the same 
virtualenv.

**Comment by Pitje06** [comment]
All of this is implemented now, and seems to work well. Do you also want to build the docs automagically? If not, this can be closed.

**Comment by jbarnoud** [comment]
The only benefit at building the doc in travis compared to let readthedoc do the build would be to have the doc built for pull requests. But you would need somewhere to serve it if you want to look at it.

**Comment by tBuLi** [comment]
Yeah that is true, but I think it's quite helpful to know if a PR breaks the docs. For example, if the docstrings in a PR do not adhere to the standards, it will tell you that now.

**Comment by jbarnoud** [comment]
Be careful then that sphinx is very good at failing with a simple warning. I had issues where sphinx failed miserably but still exited with a null code.

**Comment by tBuLi** [comment]
Haha yes I can imagine. But I run it with warnings as errors, and in nit-picky mode (-nW). So it might even be to touch on occasion, but at least we wont have false positives ;).
